# Dockerfile
 
# Use an existing node  image as a base image.
FROM node:18-alpine As development
 
# Set the working directory.
WORKDIR /app
 
# Copy the package.json file.
COPY package*.json .
 
# Install application dependencies.
RUN npm install
 
# Copy the rest of the application files.
COPY . .
 
# Expose the port.
EXPOSE 3000
 
# Run the application.
CMD ["npm", "run", "dev"]