version: "3.4"

services:
  frontend:
    build: ./
    image: frontend-melany
    container_name:  frontend-melany
    restart: unless-stopped
    environment:
      - VITE_API_URL=http://localhost:8080/api
    ports:
      - "80:80"